#!/usr/bin/env python3
"""
Device Registration Script for Warhammer Node
Customers run this script to get device information for license requests.
"""

import os
import json
import sys
import argparse
import logging
from pathlib import Path

# Add the parent directory to Python path to import license_manager
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from license_manager import DeviceLicenseManager

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

def set_device_environment(device_id):
    """Set device ID in environment and create persistent environment file"""
    try:
        # Set environment variable for current process
        os.environ['DEVICE_ID'] = device_id
        os.environ['WARHAMMER_DEVICE_ID'] = device_id
        
        # Create persistent environment file
        env_file_path = "/etc/warhammer/device.env"
        env_content = f"""# Warhammer Node Device Environment
# Generated by device registration script
# Do not edit manually - will be overwritten on device registration

DEVICE_ID={device_id}
WARHAMMER_DEVICE_ID={device_id}
"""
        
        # Ensure directory exists
        os.makedirs(os.path.dirname(env_file_path), exist_ok=True)
        
        # Write environment file
        with open(env_file_path, 'w') as f:
            f.write(env_content)
        
        # Set restrictive permissions
        os.chmod(env_file_path, 0o600)
        
        # Also create a systemd environment file for services
        systemd_env_path = "/etc/warhammer/systemd.env"
        with open(systemd_env_path, 'w') as f:
            f.write(env_content)
        os.chmod(systemd_env_path, 0o600)
        
        logger.info(f"Device environment set: DEVICE_ID={device_id}")
        return True
        
    except Exception as e:
        logger.error(f"Failed to set device environment: {e}")
        return False

def load_device_environment():
    """Load device environment from file if available"""
    try:
        env_file_path = "/etc/warhammer/device.env"
        if os.path.exists(env_file_path):
            with open(env_file_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        os.environ[key] = value
                        logger.info(f"Loaded environment: {key}={value}")
            return True
    except Exception as e:
        logger.error(f"Failed to load device environment: {e}")
    return False

def main():
    """Main device registration function"""
    parser = argparse.ArgumentParser(
        description='Generate device information for Warhammer Node license request'
    )
    parser.add_argument('--output', '-o', 
                       help='Output file path (default: device_info.json)')
    parser.add_argument('--verbose', '-v', action='store_true',
                       help='Verbose output')
    parser.add_argument('--force', '-f', action='store_true',
                       help='Force regeneration of device keys')
    parser.add_argument('--env-only', action='store_true',
                       help='Only set environment variables, skip key generation')
    
    args = parser.parse_args()
    
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    
    try:
        print("🔐 Warhammer Node Device Registration")
        print("=" * 50)
        
        # Initialize device manager
        print("📱 Initializing device manager...")
        device_manager = DeviceLicenseManager()
        
        print(f"🆔 Device ID: {device_manager.device_id}")
        print(f"📁 Keys directory: {device_manager.keys_dir}")
        
        # Set device environment variables
        print("🌍 Setting device environment...")
        if set_device_environment(device_manager.device_id):
            print("✅ Device environment set successfully!")
        else:
            print("⚠️  Warning: Failed to set device environment")
        
        if args.env_only:
            print("✅ Environment-only mode completed")
            return 0
        
        # Check if keys already exist
        if os.path.exists(f"{device_manager.keys_dir}/public_key.pem") and not args.force:
            print("✅ Device keys already exist. Use --force to regenerate.")
        else:
            print("🔑 Generating device keys...")
            if device_manager.generate_device_keys():
                print("✅ Device keys generated successfully!")
            else:
                print("❌ Failed to generate device keys!")
                return 1
        
        # Get device information
        print("📊 Collecting device information...")
        device_info = device_manager.get_device_info()
        
        if not device_info['public_key']:
            print("❌ Failed to read device public key!")
            return 1
        
        # Determine output path
        output_path = args.output or "device_info.json"
        
        # Save device information
        print(f"💾 Saving device information to {output_path}...")
        with open(output_path, 'w') as f:
            json.dump(device_info, f, indent=2)
        
        print("✅ Device information saved successfully!")
        print("\n📋 Next Steps:")
        print("1. Send the device_info.json file to CTG")
        print("2. Include your company name")
        print("3. We'll generate a license file for your device")
        print("4. Install the license on your device to activate features")
        
        # Display key information
        print(f"\n📱 Device Summary:")
        print(f"   Device ID: {device_info['device_id']}")
        print(f"   Fingerprint: {device_info['fingerprint'][:16]}...")
        
        if 'hardware_info' in device_info and device_info['hardware_info']:
            hw = device_info['hardware_info']
            if 'cpu_model' in hw:
                print(f"   CPU: {hw['cpu_model']}")
            if 'memory_mb' in hw:
                print(f"   Memory: {hw['memory_mb']} MB")
            if 'disk_size' in hw:
                print(f"   Disk: {hw['disk_size']}")
        
        print(f"\n📁 Files created:")
        print(f"   Device info: {output_path}")
        print(f"   Environment: /etc/warhammer/device.env")
        print(f"   Systemd env: /etc/warhammer/systemd.env")
        print(f"   Public key: {device_manager.keys_dir}/public_key.pem")
        print(f"   Device cert: {device_manager.keys_dir}/device_cert.pem")
        
        return 0
        
    except Exception as e:
        logger.error(f"Device registration failed: {e}")
        print(f"❌ Error: {e}")
        return 1

def create_device_info_template():
    """Create a template device info file for testing"""
    template = {
        "device_id": "example_device_1234567890abcdef",
        "public_key": "-----BEGIN PUBLIC KEY-----\n...\n-----END PUBLIC KEY-----",
        "fingerprint": "example_fingerprint_1234567890abcdef1234567890abcdef",
        "hardware_info": {
            "cpu_model": "Example CPU Model",
            "memory_mb": 8192,
            "disk_size": "500G",
            "generated_at": "2024-01-01T00:00:00"
        }
    }
    
    with open("device_info_template.json", 'w') as f:
        json.dump(template, f, indent=2)
    
    print("📝 Created device_info_template.json for testing")

if __name__ == '__main__':
    if len(sys.argv) == 1:
        # No arguments provided, run main function
        exit(main())
    elif sys.argv[1] == '--create-template':
        create_device_info_template()
    else:
        exit(main())
